# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.CharField(max_length=250)),
                ('collectionIDString', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmentName', models.CharField(max_length=250)),
                ('environmentIDString', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment'),
        ),
    ]
