# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=250)),
                ('documentIDString', models.CharField(max_length=36)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Collection')),
            ],
        ),
    ]
