# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentFile',
            field=models.FileField(default='media/default.html', upload_to=b''),
        ),
    ]
