# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_google_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentContent',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
